// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Paul"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/debug": {
            "get": {
                "tags": [
                    "debug"
                ],
                "summary": "Dummy check",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/notifications": {
            "post": {
                "description": "Create a notification and store it in MongoDB",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Create a new notification",
                "parameters": [
                    {
                        "description": "Notification payload",
                        "name": "notification",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/notification-system_internal_notification_model.Notification"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/notification-system_internal_notification_model.Notification"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Just ping",
                "tags": [
                    "test"
                ],
                "summary": "Ping test",
                "responses": {
                    "200": {
                        "description": "pong",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/test": {
            "get": {
                "description": "Dummy route",
                "tags": [
                    "test"
                ],
                "summary": "Test",
                "responses": {
                    "200": {
                        "description": "test",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user-preferences": {
            "post": {
                "description": "Stores user preferences for a given user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-preferences"
                ],
                "summary": "Create user preference",
                "parameters": [
                    {
                        "description": "User Preference",
                        "name": "user_preference",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/notification-system_internal_userpreference_model.UserPreference"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/user-preferences/{id}": {
            "put": {
                "description": "Update an existing user preference by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-preferences"
                ],
                "summary": "Update user preferences",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User Preference ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User Preference Payload",
                        "name": "userPreference",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/notification-system_internal_userpreference_model.UserPreference"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "fiber.Map": {
            "type": "object",
            "additionalProperties": true
        },
        "notification-system_internal_notification_model.Notification": {
            "type": "object",
            "properties": {
                "channels": {
                    "description": "email, sms, etc.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "created_by_id": {
                    "type": "string"
                },
                "created_by_name": {
                    "type": "string"
                },
                "created_date": {
                    "description": "CreatedDate is the time the notification was created\nexample: 2025-07-08T14:00:00Z",
                    "type": "string"
                },
                "maximum_retries": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "modified_by_id": {
                    "type": "string"
                },
                "modified_by_name": {
                    "type": "string"
                },
                "modified_date": {
                    "type": "string"
                },
                "notification_id": {
                    "description": "custom ID",
                    "type": "string"
                },
                "priority": {
                    "type": "string"
                },
                "send_at": {
                    "type": "string"
                },
                "type": {
                    "description": "transactional, promotional, etc.",
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "notification-system_internal_userpreference_model.Channel": {
            "type": "object",
            "properties": {
                "promotional": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "system_alerts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "transactional": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "notification-system_internal_userpreference_model.DailyLimit": {
            "type": "object",
            "properties": {
                "promotional_limit": {
                    "type": "string"
                },
                "promotional_sent_today": {
                    "type": "string"
                }
            }
        },
        "notification-system_internal_userpreference_model.DeliveryTime": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "end_time": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "time_zone": {
                    "type": "string"
                }
            }
        },
        "notification-system_internal_userpreference_model.NoDisturb": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "end_date_time": {
                    "type": "string"
                },
                "start_date_time": {
                    "type": "string"
                },
                "time_zone": {
                    "type": "string"
                }
            }
        },
        "notification-system_internal_userpreference_model.Preference": {
            "type": "object",
            "properties": {
                "channels": {
                    "$ref": "#/definitions/notification-system_internal_userpreference_model.Channel"
                },
                "daily_limit_details": {
                    "$ref": "#/definitions/notification-system_internal_userpreference_model.DailyLimit"
                },
                "delivery_time": {
                    "$ref": "#/definitions/notification-system_internal_userpreference_model.DeliveryTime"
                },
                "no_disturb_details": {
                    "$ref": "#/definitions/notification-system_internal_userpreference_model.NoDisturb"
                }
            }
        },
        "notification-system_internal_userpreference_model.UserPreference": {
            "type": "object",
            "properties": {
                "created_by_id": {
                    "type": "string"
                },
                "created_by_name": {
                    "type": "string"
                },
                "created_date": {
                    "type": "string"
                },
                "modified_by_id": {
                    "type": "string"
                },
                "modified_by_name": {
                    "type": "string"
                },
                "modified_date": {
                    "type": "string"
                },
                "preferences": {
                    "$ref": "#/definitions/notification-system_internal_userpreference_model.Preference"
                },
                "user_id": {
                    "type": "string"
                },
                "user_preference_id": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:4001",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Notification System API",
	Description:      "API docs for Notification System",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
